- hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - shell: |
        curl ipinfo.io/ip
      register: out
       
    - debug:
        var: out
        
    - shell: |
        curl -v {{ item }}
      register: out
      loop:
        - "lht.app.lufthansa.com"
        - "quay.apps.svc.az.lhtcloud.com"
        - "google.com"
       
    - debug:
        var: out
        
    - shell: |
        oc version
      register: out
       
    - debug:
        var: out
