- hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        var: ansible_python_interpreter
        
    - shell: |
        curl ipinfo.io/ip
      register: out
       
    - debug:
        var: out
